@startuml
package Family{
  class Family {
    FirstSurname : String
    SecondSurname : String
    Email: String
  }
  class Parent {
    Name : String
    Surname: String
  } 
  class Child {
    Name : String
    Year : Integer
    Repetition : Integer
  } 
  class BankAccount {
    SwiftBIC : String
    IBAN : String
  }
  class SEPA{
    OrdenDeDomiciliación: String
    AuthorizationDate: Date
  }

  BankAccount "1" *-- "1" SEPA
  Family *-- "N" Child
  Family *-- "1..2" Parent
  Parent *-- "0..N" BankAccount
  Family o-- BankAccount

  class Socio{
    AcacemicCourse: enlace
  }

  class Padrastro
}

package Activity{
  class ActivityPadre?
  class Activity {
    Name: String
  }
  abstract class "TypeAsociado"
  class Price {
    Descuento: boolean
  }
  class Familiar
  class Individual
  class ActivityRegistration {
    Amount: Float
  }
  abstract class Registered
  class RegisteredFamily
  class RegisteredChild
  class AcademicCourse {
    InitialYear: Integer
  }
  class PaymentOrder {
    Amount: Float
  }
  abstract class Subvencion
  class Cultural
  class Deportiva
  class NoSubvencionable
  Subvencion<|-- Cultural
  Subvencion<|-- Deportiva
  Subvencion<|-- NoSubvencionable

  RegisteredFamily o-up- Family
  RegisteredChild o-up- Child
  Activity *-- Price
  Activity o-- TypeAsociado
  TypeAsociado<|-- Familiar
  TypeAsociado<|-- Individual
  Registered <|-- RegisteredFamily
  Registered <|-- RegisteredChild
  ActivityRegistration o-- Activity
  ActivityRegistration *-- Registered
  Activity o-- AcademicCourse
  ActivityRegistration o-- BankAccount
  ActivityRegistration o-- PaymentOrder
}
@enduml
