from model_bakery.recipe import Recipe, foreign_key

from ampa_members_manager.activity.models.unique_activity import UniqueActivity
from ampa_members_manager.activity_registration.models.activity_registration import ActivityRegistration
from ampa_members_manager.baker_recipes import single_activity_with_unique_activity
