@startuml
left to right direction
actor Admin
package AcademicCourse{
  Admin --> (Create AcademicCourse)
  Admin --> (Establish ActiveCourse)
  Admin --> (Establish AcademicCourse Fee)
}
package Family {
  Admin --> (Register Family)
  Admin --> (Add Child to a Family)
  Admin --> (Add Parent to a Family)
  Admin --> (Assign BankAccount to a Parent)
  Admin --> (Assign AuthorizationNumber to a BankAccount)
  Admin --> (Change Family BankAccount)
  Admin --> (Add Membership for a Family)
}
package Activity {
  Admin --> (Register Activity in the system)
}
package ActivityRegistration {
  Admin --> (Join Activity)
  Admin --> (Establish amount of an ActivityRegistration)
}
package Charge {
}
Admin --> Charge
@enduml