@startuml
left to right direction
actor Admin
package AcademicCourse{
    Admin --> (Create AcademicCourse)
    Admin --> (Establish ActiveCourse)
    Admin --> (Establish AcademicCourse Fee)
}
package Family {
    Admin --> (Register Family)
    Admin --> (Add Child to a Family)
    Admin --> (Add Parent to a Family)
    Admin --> (Add Holder with a BankAccount)
    Admin --> (Change Family Holder)
    Admin --> (Add Membership for a Family)
}
package Activity {
    package AfterSchool {
        Admin --> (Register AfterSchool in the system)
        Admin --> (Register AfterSchoolEdition in the system)
        Admin --> (Register AfterSchoolRegistration in the system)
    }
    package Custody {
        Admin --> (Register CustodyEdition in the system)
        Admin --> (Register CustodyRegistration in the system)
    }
    package Camps {
        Admin --> (Register CampsEdition in the system)
        Admin --> (Register CampsRegistration in the system)
    }
}
package Charge {
    Admin --> Charge
}
package Importation {
    Admin --> (Import Custody)
    Admin --> (See CustodyImportationRows and actions)
    Admin --> (Modify CustodyImportationRow actions)
    Admin --> (Confirm CustodyImportationRow actions)
}
@enduml
