@startuml
package AcademicCourse
package Family
package Activity
package Charge
package Importation

Charge --> Family
Activity --> Family
Activity --> AcademicCourse
Family --> AcademicCourse
Charge --> Activity
Charge --> AcademicCourse
Importation --> Activity
Importation --> Family
Importation --> AcademicCourse
@enduml
