# Generated by Django 4.0.6 on 2022-11-12 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0010_remove_family_email_remove_family_secondary_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Order'),
            preserve_default=False,
        ),
    ]
