# Generated by Django 4.0.6 on 2022-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0011_add_order_to_authorization'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('academic_course', 'family'), name='unique_family_membership_for_course'),
        ),
    ]
