# Generated by Django 4.0.6 on 2022-11-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0012_membership_unique_family_membership_for_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='AfterSchool activity name')),
                ('funding', models.IntegerField(choices=[(1, 'No funding'), (2, 'Cultural'), (3, 'Sport')], verbose_name='Funding')),
            ],
            options={
                'verbose_name': 'AfterSchool',
                'verbose_name_plural': 'AfterSchools',
            },
        ),
    ]
