# Generated by Django 4.0.6 on 2022-11-24 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0014_add_after_school_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_school_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.afterschooledition', verbose_name='AfterSchoolEdition')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.bankaccount', verbose_name='BankAccount')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.child', verbose_name='Child')),
            ],
        ),
        migrations.AddConstraint(
            model_name='afterschoolregistration',
            constraint=models.UniqueConstraint(fields=('after_school_edition', 'child'), name='unique_after_school_edition_for_child'),
        ),
    ]
