# Generated by Django 4.0.6 on 2022-12-16 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0015_add_after_school_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSchoolRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('after_school_editions', models.ManyToManyField(related_name='after_school_remittance', to='ampa_manager.afterschooledition', verbose_name='AfterSchoolEditions')),
            ],
            options={
                'verbose_name': 'AfterSchool remittance',
                'verbose_name_plural': 'AfterSchool remittances',
            },
        ),
        migrations.CreateModel(
            name='AfterSchoolReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Total (€)')),
                ('state', models.IntegerField(choices=[(1, 'Created'), (2, 'Sent'), (3, 'Paid')], default=1, verbose_name='State')),
                ('after_school_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.afterschoolregistration', verbose_name='After School registrations')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.afterschoolremittance', verbose_name='After School remittance')),
            ],
            options={
                'verbose_name': 'After School Receipt',
                'verbose_name_plural': 'After School Receipts',
            },
        ),
    ]
