# Generated by Django 4.0.6 on 2022-12-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0020_add_db_table_to_more_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorization',
            old_name='date',
            new_name='sign_date',
        ),
    ]
