# Generated by Django 4.0.6 on 2022-12-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0021_rename_date_authorization_sign_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afterschool',
            options={'verbose_name': 'After-school', 'verbose_name_plural': 'After-schools'},
        ),
        migrations.AlterModelOptions(
            name='afterschooledition',
            options={'verbose_name': 'After-school edition', 'verbose_name_plural': 'After-school editions'},
        ),
        migrations.AlterModelOptions(
            name='afterschoolreceipt',
            options={'verbose_name': 'After-school receipt', 'verbose_name_plural': 'After-school receipts'},
        ),
        migrations.AlterModelOptions(
            name='afterschoolregistration',
            options={'verbose_name': 'After-school registration', 'verbose_name_plural': 'After-school registrations'},
        ),
        migrations.AlterModelOptions(
            name='afterschoolremittance',
            options={'verbose_name': 'After-school remittance', 'verbose_name_plural': 'After-school remittances'},
        ),
        migrations.AlterField(
            model_name='afterschooledition',
            name='after_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.afterschool', verbose_name='After-school'),
        ),
        migrations.AlterField(
            model_name='afterschooledition',
            name='levels',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Levels'),
        ),
        migrations.AlterField(
            model_name='afterschoolregistration',
            name='after_school_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.afterschooledition', verbose_name='After-school edition'),
        ),
        migrations.AlterField(
            model_name='afterschoolregistration',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.bankaccount', verbose_name='Bank account'),
        ),
    ]
