# Generated by Django 4.1.5 on 2023-01-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0022_alter_afterschool_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authorization',
            new_name='AuthorizationOld',
        ),
        migrations.AlterModelOptions(
            name='authorizationold',
            options={'verbose_name': 'AuthorizationOld', 'verbose_name_plural': 'OldAuthorizations'},
        ),
        migrations.AlterModelTable(
            name='authorizationold',
            table='authorization_old',
        ),
    ]
