# Generated by Django 4.1.5 on 2023-01-20 23:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0023_rename_authorization_authorizationold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Order')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)], verbose_name='Year')),
                ('sign_date', models.DateField(default=datetime.date.today)),
                ('document', models.FileField(blank=True, null=True, upload_to='authorizations/', verbose_name='Document')),
                ('state', models.IntegerField(choices=[(1, 'Not sent'), (2, 'Sent'), (3, 'Signed')], default=1, verbose_name='State')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.bankaccount', verbose_name='Bank Account')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.parent', verbose_name='Holder')),
            ],
            options={
                'verbose_name': 'Holder',
                'verbose_name_plural': 'Holders',
                'db_table': 'holder',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='default_holder',
            field=models.ForeignKey(blank=True, help_text='Save the family to see its bank accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ampa_manager.holder', verbose_name='Default holder'),
        ),
        migrations.AddConstraint(
            model_name='holder',
            constraint=models.UniqueConstraint(fields=('order', 'year'), name='holder_unique_order_in_a_year'),
        ),
        migrations.AddConstraint(
            model_name='holder',
            constraint=models.UniqueConstraint(fields=('parent', 'bank_account'), name='holder_unique_parent_and_bank_account'),
        ),
    ]
