# Generated by Django 4.1.5 on 2023-01-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0024_add_holder_and_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterschoolregistration',
            name='holder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.holder', verbose_name='Holder'),
            preserve_default=False,
        ),
    ]
