# Generated by Django 4.1.5 on 2023-01-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0026_alter_holder_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holder',
            name='holder_unique_order_in_a_year',
        ),
        migrations.RemoveConstraint(
            model_name='holder',
            name='holder_unique_parent_and_bank_account',
        ),
        migrations.RenameField(
            model_name='holder',
            old_name='order',
            new_name='authorization_order',
        ),
        migrations.AddConstraint(
            model_name='holder',
            constraint=models.UniqueConstraint(fields=('parent', 'bank_account'), name='unique_parent_and_bank_account'),
        ),
        migrations.AddConstraint(
            model_name='holder',
            constraint=models.UniqueConstraint(fields=('authorization_order', 'year'), name='unique_authorization_order_in_a_year'),
        ),
    ]
