# Generated by Django 4.1.5 on 2023-01-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0027_remove_holder_holder_unique_order_in_a_year_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holder',
            name='unique_authorization_order_in_a_year',
        ),
        migrations.RenameField(
            model_name='holder',
            old_name='year',
            new_name='authorization_year',
        ),
        migrations.AddConstraint(
            model_name='holder',
            constraint=models.UniqueConstraint(fields=('authorization_order', 'authorization_year'), name='unique_authorization_order_in_a_year'),
        ),
    ]
