# Generated by Django 4.1.5 on 2023-01-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0028_remove_holder_unique_authorization_order_in_a_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holder',
            old_name='state',
            new_name='authorization_state',
        ),
    ]
