# Generated by Django 4.1.5 on 2023-01-23 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0030_rename_sign_date_holder_authorization_sign_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holder',
            old_name='document',
            new_name='authorization_document',
        ),
    ]
