# Generated by Django 4.1.5 on 2023-01-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0032_remove_family_default_bank_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['iban'], 'verbose_name': 'Bank account', 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='owner',
        ),
    ]
