# Generated by Django 4.1.5 on 2023-01-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0034_activityregistration_holder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizationOld',
        ),
    ]
