# Generated by Django 4.1.5 on 2023-01-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0035_delete_authorizationold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityregistration',
            name='bank_account',
        ),
    ]
