# Generated by Django 4.1.5 on 2023-01-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0036_remove_activityregistration_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afterschoolregistration',
            name='bank_account',
        ),
    ]
