# Generated by Django 4.1.5 on 2023-01-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0038_bankbiccode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(blank=True, max_length=300, null=True, verbose_name='Levels')),
                ('price_for_member', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price for members')),
                ('price_for_no_member', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price for no members')),
                ('period_and_level', models.CharField(max_length=300, verbose_name='Period')),
                ('max_days_for_charge', models.PositiveIntegerField(verbose_name='Max days for charge')),
                ('academic_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.academiccourse', verbose_name='Academic course')),
            ],
            options={
                'verbose_name': 'Custody edition',
                'verbose_name_plural': 'Custody editions',
                'db_table': 'custody_edition',
            },
        ),
        migrations.AddConstraint(
            model_name='custodyedition',
            constraint=models.UniqueConstraint(fields=('academic_course', 'period_and_level'), name='unique_academic_course_with_period_and_level'),
        ),
    ]
