# Generated by Django 4.1.5 on 2023-02-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0039_add_custody_edition'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='custodyedition',
            name='unique_academic_course_with_period_and_level',
        ),
        migrations.RenameField(
            model_name='custodyedition',
            old_name='period_and_level',
            new_name='period',
        ),
        migrations.AddField(
            model_name='custodyedition',
            name='primary',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='custodyedition',
            constraint=models.UniqueConstraint(fields=('academic_course', 'period', 'primary'), name='unique_academic_course_with_period_and_primary'),
        ),
    ]
