# Generated by Django 4.1.5 on 2023-02-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0040_remove_custodyedition_unique_academic_course_with_period_and_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assisted_days', models.PositiveIntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.child', verbose_name='Child')),
                ('custody_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.custodyedition', verbose_name='Custody edition')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.holder', verbose_name='Holder')),
            ],
            options={
                'verbose_name': 'Custody registration',
                'verbose_name_plural': 'Custody registrations',
                'db_table': 'custody_registration',
            },
        ),
        migrations.AddConstraint(
            model_name='custodyregistration',
            constraint=models.UniqueConstraint(fields=('custody_edition', 'child'), name='unique_custody_edition_for_child'),
        ),
    ]
