# Generated by Django 4.1.5 on 2023-02-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0041_custodyregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('custody_editions', models.ManyToManyField(related_name='custody_remittance', to='ampa_manager.custodyedition', verbose_name='CustodyEditions')),
            ],
            options={
                'verbose_name': 'Custody remittance',
                'verbose_name_plural': 'Custody remittances',
                'db_table': 'custody_remittance',
            },
        ),
    ]
