# Generated by Django 4.1.5 on 2023-02-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0044_alter_holder_authorization_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityremittance',
            name='activity_periods',
        ),
        migrations.DeleteModel(
            name='ActivityReceipt',
        ),
        migrations.DeleteModel(
            name='ActivityRemittance',
        ),
    ]
