# Generated by Django 4.1.5 on 2023-02-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0045_remove_activityremittance_activity_periods_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityRegistration',
        ),
    ]
