# Generated by Django 4.1.5 on 2023-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0048_remove_custodyedition_unique_academic_course_with_period_and_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterschoolremittance',
            name='concept',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Concept'),
        ),
        migrations.AddField(
            model_name='afterschoolremittance',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AddField(
            model_name='custodyremittance',
            name='concept',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Concept'),
        ),
        migrations.AddField(
            model_name='custodyremittance',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment date'),
        ),
    ]
