# Generated by Django 4.1.5 on 2023-02-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0048_remove_custodyedition_unique_academic_course_with_period_and_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodyedition',
            name='cycle',
            field=models.IntegerField(choices=[(1, 'Pre-school'), (2, 'Primary education')], verbose_name='Cycle'),
        ),
    ]
