# Generated by Django 4.1.5 on 2023-02-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0049_afterschoolremittance_concept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterschoolremittance',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='custodyremittance',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment date'),
        ),
    ]
