# Generated by Django 4.1.5 on 2023-03-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0052_alter_custodyedition_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipremittance',
            name='identifier',
        ),
        migrations.AddField(
            model_name='membershipremittance',
            name='concept',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Concept'),
        ),
        migrations.AddField(
            model_name='membershipremittance',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='membershipremittance',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='membershipremittance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
