# Generated by Django 4.1.5 on 2023-05-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0053_remove_membershipremittance_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampsEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(max_length=300, verbose_name='Levels')),
                ('price_for_member', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price for members')),
                ('price_for_no_member', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price for no members')),
                ('academic_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.academiccourse', verbose_name='Academic course')),
            ],
            options={
                'verbose_name': 'Camps edition',
                'verbose_name_plural': 'Camps editions',
                'db_table': 'camps_edition',
            },
        ),
        migrations.AddConstraint(
            model_name='campsedition',
            constraint=models.UniqueConstraint(fields=('academic_course', 'levels'), name='unique_academic_course_with_levels'),
        ),
    ]
