# Generated by Django 4.1.5 on 2023-05-15 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0054_add_camps_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camps_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.campsedition', verbose_name='Camps edition')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.child', verbose_name='Child')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.holder', verbose_name='Holder')),
            ],
            options={
                'verbose_name': 'Camps registration',
                'verbose_name_plural': 'Camps registrations',
                'db_table': 'camps_registration',
            },
        ),
        migrations.AddConstraint(
            model_name='campsregistration',
            constraint=models.UniqueConstraint(fields=('camps_edition', 'child'), name='unique_camps_edition_for_child'),
        ),
    ]
