# Generated by Django 4.1.5 on 2023-05-16 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0055_add_camps_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampsRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('concept', models.CharField(blank=True, max_length=50, null=True, verbose_name='Concept')),
                ('camps_editions', models.ManyToManyField(related_name='camps_remittance', to='ampa_manager.campsedition', verbose_name='CampsEdition')),
            ],
            options={
                'verbose_name': 'Camps remittance',
                'verbose_name_plural': 'Camps remittances',
                'db_table': 'camps_remittance',
            },
        ),
        migrations.CreateModel(
            name='CampsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Total (€)')),
                ('state', models.IntegerField(choices=[(1, 'Created'), (2, 'Sent'), (3, 'Paid')], default=1, verbose_name='State')),
                ('camps_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.campsregistration', verbose_name='Camps registrations')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.campsremittance', verbose_name='Camps remittance')),
            ],
            options={
                'verbose_name': 'Camps receipt',
                'verbose_name_plural': 'Camps receipts',
                'db_table': 'camps_receipt',
            },
        ),
    ]
