# Generated by Django 4.2 on 2023-07-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0057_afterschoolremittance_sepa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='custody_holder',
            field=models.ForeignKey(blank=True, help_text='Save the family to see its bank accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_holder', to='ampa_manager.holder', verbose_name='Custody holder'),
        ),
        migrations.AlterField(
            model_name='campsedition',
            name='levels',
            field=models.CharField(help_text='For example: Primary, Pre-school, LH1-LH3', max_length=300, verbose_name='Levels'),
        ),
    ]
