# Generated by Django 4.2 on 2023-12-01 00:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0058_family_custody_holder_alter_campsedition_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyImportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('custody_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.custodyedition', verbose_name='Custody Edition')),
            ],
            options={
                'verbose_name': 'Custody importation',
                'verbose_name_plural': 'Custody importations',
                'db_table': 'custody_importation',
            },
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['name', 'family__surnames'], 'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.CreateModel(
            name='CustodyImportationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('year_of_birth', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)], verbose_name='Year of birth')),
                ('level', models.IntegerField(choices=[('ID_HH2', 'HH2'), ('ID_HH3', 'HH3'), ('ID_HH4', 'HH4'), ('ID_HH5', 'HH5'), ('ID_LH1', 'LH1'), ('ID_LH2', 'LH2'), ('ID_LH3', 'LH3'), ('ID_LH4', 'LH4'), ('ID_LH5', 'LH5'), ('ID_LH6', 'LH6')], verbose_name='Level')),
                ('surnames', models.CharField(max_length=500, verbose_name='Surnames')),
                ('days_attended', models.PositiveIntegerField(verbose_name='Days attended')),
                ('name_and_surnames', models.CharField(max_length=500, unique=True, verbose_name='Name and surnames')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('iban', localflavor.generic.models.IBANField(include_countries=None, max_length=34, unique=True, use_nordea_extensions=False, verbose_name='IBAN')),
                ('row', models.PositiveIntegerField(verbose_name='Row')),
                ('importation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.custodyimportation', verbose_name='Importation')),
            ],
            options={
                'verbose_name': 'Custody importation row',
                'verbose_name_plural': 'Custody importation rows',
                'db_table': 'custody_importation_row',
            },
        ),
        migrations.AddConstraint(
            model_name='custodyimportationrow',
            constraint=models.UniqueConstraint(fields=('importation', 'row'), name='unique_importation_row'),
        ),
    ]
