# Generated by Django 4.2 on 2024-01-11 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0060_alter_custodyimportationrow_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name': 'Fee', 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterField(
            model_name='custodyedition',
            name='cycle',
            field=models.CharField(choices=[('PRE', 'Pre-school'), ('PRI', 'Primary education'), ('ALL', 'All cycles')], default='PRI', max_length=3, verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='custodyregistration',
            name='custody_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ampa_manager.custodyedition', verbose_name='Custody edition'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='academic_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.academiccourse', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='authorization_year',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)], verbose_name='Year'),
        ),
    ]
