# Generated by Django 4.2 on 2024-01-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0061_alter_fee_options_alter_custodyedition_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyImportationActionChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_child_data', models.JSONField(default=dict, null=True, verbose_name='Update Child')),
                ('create_child_data', models.JSONField(default=dict, null=True, verbose_name='Create Child')),
                ('child_to_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_to_update', to='ampa_manager.child', verbose_name='Child to update')),
                ('child_to_use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_to_use', to='ampa_manager.child', verbose_name='Use Child')),
                ('family_to_create_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.family', verbose_name='Family to create child')),
            ],
            options={
                'verbose_name': 'Custody importation action child',
                'verbose_name_plural': 'Custody importation action children',
            },
        ),
        migrations.CreateModel(
            name='CustodyImportationActionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.custodyimportationactionchild')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.custodyimportationrow')),
            ],
        ),
        migrations.AddConstraint(
            model_name='custodyimportationactionchild',
            constraint=models.CheckConstraint(check=models.Q(('child_to_use__isnull', False), models.Q(('update_child_data__isnull', False), ('child_to_update__isnull', False)), models.Q(('create_child_data__isnull', False), ('family_to_create_child__isnull', False)), _connector='OR'), name='child_constraint'),
        ),
    ]
