# Generated by Django 4.2 on 2024-01-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0062_custodyimportationactionchild_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterschoolregistration',
            name='after_school_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ampa_manager.afterschooledition', verbose_name='After-school edition'),
        ),
    ]
