# Generated by Django 4.2 on 2024-01-30 14:58

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0063_alter_afterschoolregistration_after_school_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remittances_party_id', models.CharField(max_length=500, verbose_name='Party identification')),
                ('remittances_generic_org_id', models.CharField(max_length=500, verbose_name='Generic organisation identification')),
                ('remittances_bic', models.CharField(max_length=500, verbose_name='BIC')),
                ('remittances_iban', localflavor.generic.models.IBANField(include_countries=None, max_length=34, unique=True, use_nordea_extensions=False, verbose_name='IBAN')),
                ('custody_members_discount_percent', models.FloatField(help_text='Percentage discounted to members in the price of the custody', verbose_name='Members discount')),
                ('custody_max_days_to_charge_percent', models.IntegerField(help_text='Maximum number of days in a month (as a percentage) to charge to each user', verbose_name='Max days to charge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='afterschoolremittance',
            name='sepa_id',
            field=models.CharField(blank=True, help_text='Leave empty to auto-generate', max_length=300, null=True, verbose_name='Sepa_id'),
        ),
        migrations.AlterField(
            model_name='campsremittance',
            name='sepa_id',
            field=models.CharField(blank=True, help_text='Leave empty to auto-generate', max_length=300, null=True, verbose_name='Sepa_id'),
        ),
        migrations.AlterField(
            model_name='custodyremittance',
            name='sepa_id',
            field=models.CharField(blank=True, help_text='Leave empty to auto-generate', max_length=300, null=True, verbose_name='Sepa_id'),
        ),
        migrations.AlterField(
            model_name='membershipremittance',
            name='sepa_id',
            field=models.CharField(blank=True, help_text='Leave empty to auto-generate', max_length=300, null=True, verbose_name='Sepa_id'),
        ),
    ]
