# Generated by Django 4.2 on 2024-01-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0064_dynamicsetting_alter_afterschoolremittance_sepa_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicsetting',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.RenameField(
            model_name='family',
            old_name='default_holder',
            new_name='membership_holder',
        ),
        migrations.AlterField(
            model_name='custodyedition',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Los precios se pueden calcular automáticamente con la acción "Calcular precios" a partir de este coste y los días asistidos. Los no socios tienen un recargo del 27.0% ', max_digits=6, null=True, verbose_name='Cost'),
        ),
    ]
