# Generated by Django 4.2 on 2024-01-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0066_family_after_school_holder_family_camps_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='membership_holder',
            field=models.ForeignKey(blank=True, help_text='Guarda la familia para ver sus cuentas bancarias. This account will be used if no other is specified', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ampa_manager.holder', verbose_name='Membership holder'),
        ),
    ]
