# Generated by Django 4.2 on 2024-02-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0070_custodyedition_days_with_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodyedition',
            name='max_days_for_charge',
        ),
    ]
