# Generated by Django 4.2 on 2024-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0071_remove_custodyedition_max_days_for_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Normalized name'),
        ),
        migrations.AddField(
            model_name='family',
            name='normalized_surnames',
            field=models.CharField(blank=True, max_length=500, verbose_name='Normalized surnames'),
        ),
        migrations.AddField(
            model_name='parent',
            name='normalized_name_and_surnames',
            field=models.CharField(blank=True, max_length=500, verbose_name='Normalized name and surnames'),
        ),
    ]
