# Generated by Django 4.2 on 2024-09-04 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def copy_holder(apps, _):
    membership_receipt_class = apps.get_model('ampa_manager', 'MembershipReceipt')
    for receipt in membership_receipt_class.objects.all():
        receipt.holder = receipt.family.membership_holder
        receipt.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ampa_manager', '0074_alter_dynamicsetting_custody_max_days_to_charge_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipreceipt',
            name='holder',
            field=models.ForeignKey(
                default=126, on_delete=django.db.models.deletion.CASCADE, to='ampa_manager.holder',
                verbose_name='Holder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campsregistration',
            name='camps_edition',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='registrations',
                to='ampa_manager.campsedition', verbose_name='Camps edition'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='authorization_order',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1999)], verbose_name='Order'),
        ),
        migrations.RunPython(copy_holder),
    ]
