# Generated by Django 4.2 on 2024-11-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0075_membershipreceipt_holder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afterschool',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['name', 'family__surnames'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent/Mother', 'verbose_name_plural': 'Parents/Mothers'},
        ),
        migrations.RemoveField(
            model_name='afterschoolreceipt',
            name='state',
        ),
        migrations.RemoveField(
            model_name='campsreceipt',
            name='state',
        ),
        migrations.RemoveField(
            model_name='custodyreceipt',
            name='state',
        ),
        migrations.RemoveField(
            model_name='membershipreceipt',
            name='state',
        ),
    ]
