# Generated by Django 4.2 on 2024-11-06 12:29

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0076_alter_afterschool_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodyedition',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Prices can be automatically calculated with the action "Calculate prices" based on this cost and assisted days. No members have a surcharge', max_digits=6, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='dynamicsetting',
            name='remittances_iban',
            field=localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN'),
        ),
    ]
