# Generated by Django 4.2 on 2024-11-06 12:30

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0077_alter_custodyedition_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsetting',
            name='remittances_custody_bic',
            field=models.CharField(default='Completar', max_length=500, verbose_name='Custody BIC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamicsetting',
            name='remittances_custody_iban',
            field=localflavor.generic.models.IBANField(default='completar', include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='Custody IBAN'),
            preserve_default=False,
        ),
    ]
