# Generated by Django 4.2 on 2024-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0079_afterschooledition_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterschooledition',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Code'),
        ),
        migrations.AddConstraint(
            model_name='afterschooledition',
            constraint=models.UniqueConstraint(fields=('academic_course', 'code'), name='unique_code_in_academic_course'),
        ),
    ]
