# Generated by Django 4.2 on 2024-11-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_manager', '0080_alter_afterschooledition_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustodyImportation',
        ),
        migrations.DeleteModel(
            name='CustodyImportationActionChild',
        ),
        migrations.DeleteModel(
            name='CustodyImportationActionGroup',
        ),
        migrations.DeleteModel(
            name='CustodyImportationRow',
        ),
    ]
