from ampa_members_manager.activity.baker_recipes import payable_part_with_unique_activity_local_recipe, \
    payable_part_with_repetitive_activity_local_recipe, \
    activity_registration_with_payable_part_local_recipe

payable_part_with_unique_activity_recipe = payable_part_with_unique_activity_local_recipe
payable_part_with_repetitive_activity_recipe = payable_part_with_repetitive_activity_local_recipe
activity_registration_with_payable_part_recipe = activity_registration_with_payable_part_local_recipe

payable_part_with_unique_activity = 'ampa_members_manager.payable_part_with_unique_activity_recipe'
payable_part_with_repetitive_activity = 'ampa_members_manager.payable_part_with_repetitive_activity_recipe'
activity_registration_with_payable_part = 'ampa_members_manager.activity_registration_with_payable_part_recipe'
