from ampa_members_manager.charge.baker_recipes import membership_receipt_family_bank_account_local_recipe
from ampa_members_manager.family.baker_recipes import bank_account_local_recipe, family_bank_account_local_recipe

bank_account_recipe_name = bank_account_local_recipe
family_bank_account_recipe_name = family_bank_account_local_recipe
bank_account_recipe = 'ampa_members_manager.bank_account_recipe_name'
family_bank_account_recipe = 'ampa_members_manager.family_bank_account_recipe_name'

membership_receipt_family_bank_account_recipe_name = membership_receipt_family_bank_account_local_recipe
membership_receipt_family_bank_account_recipe = 'ampa_members_manager.membership_receipt_family_bank_account_recipe_name'
