from ampa_members_manager.activity.baker_recipes import unique_activity_local_recipe, repetitive_activity_local_recipe, \
    single_activity_with_unique_activity_local_recipe, single_activity_with_repetitive_activity_local_recipe, \
    activity_registration_with_single_activity_local_recipe

unique_activity = unique_activity_local_recipe
repetitive_activity = repetitive_activity_local_recipe
single_activity_with_unique_activity_recipe = single_activity_with_unique_activity_local_recipe
single_activity_with_repetitive_activity_recipe = single_activity_with_repetitive_activity_local_recipe
activity_registration_with_single_activity_recipe = activity_registration_with_single_activity_local_recipe

single_activity_with_unique_activity = 'ampa_members_manager.single_activity_with_unique_activity_recipe'
single_activity_with_repetitive_activity = 'ampa_members_manager.single_activity_with_repetitive_activity_recipe'
activity_registration_with_single_activity = 'ampa_members_manager.activity_registration_with_single_activity_recipe'
