TEXT_XML = 'text/xml'
SEPA = 'SEPA'
CORE = 'CORE'
EURO = 'EUR'
PAIS = 'ES'
RECEIPTS_SET_AS_SENT_MESSAGE = "%(num_receipts)s receipts set as sent"
RECEIPTS_SET_AS_PAID_MESSAGE = "%(num_receipts)s receipts set as paid"
ERROR_REMITTANCE_NOT_FILLED = "Name, concept and payment date must be filled in remittance"
ERROR_ONLY_ONE_REMITTANCE = "Only can select one remittance"
