# Generated by Django 4.0.6 on 2022-08-25 08:18

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='swift_bic',
            field=localflavor.generic.models.BICField(blank=True, max_length=11, null=True, verbose_name='SWIFT/BIC'),
        ),
    ]
