# Generated by Django 4.0.3 on 2022-03-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0001_add_academic_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ampa_members_manager.academiccourse')),
            ],
        ),
    ]
