# Generated by Django 4.0.6 on 2022-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_defaulter',
            field=models.BooleanField(default=False, verbose_name='Defaulter'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Activity name'),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Period name'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='state',
            field=models.IntegerField(choices=[(1, 'Not sent'), (2, 'Sent'), (3, 'Signed')], default=1, verbose_name='State'),
        ),
    ]
