# Generated by Django 4.0.6 on 2022-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='state',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Send'), (3, 'Paid')], default=1, verbose_name='State'),
        ),
    ]
