# Generated by Django 4.0.6 on 2022-08-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0002_alter_bankaccount_swift_bic'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityremittance',
            name='identifier',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='membershipremittance',
            name='identifier',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Identifier'),
        ),
    ]
