# Generated by Django 4.0.6 on 2022-10-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0002_family_is_defaulter_alter_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['owner__name_and_surnames', 'iban'], 'verbose_name': 'Bank account', 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.AlterField(
            model_name='activityreceipt',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Total (€)'),
        ),
    ]
