# Generated by Django 4.0.6 on 2022-08-25 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0003_activityremittance_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
