# Generated by Django 4.0.3 on 2022-03-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0003_add_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='first_surname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='family',
            name='second_surname',
            field=models.CharField(max_length=500),
        ),
    ]
