# Generated by Django 4.0.3 on 2022-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0005_add_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('first_surname', models.CharField(max_length=500)),
                ('second_surname', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=12)),
                ('family', models.ManyToManyField(to='ampa_members_manager.family')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.UniqueConstraint(fields=('name', 'first_surname', 'second_surname'), name='unique_parent'),
        ),
    ]
