# Generated by Django 4.0.6 on 2022-10-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0005_bankaccount_created_bankaccount_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
