# Generated by Django 4.0.6 on 2022-10-28 15:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0006_parent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='additional_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Other phone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
    ]
