# Generated by Django 4.0.3 on 2022-03-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0007_add_bank_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='family',
            new_name='families',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='parent',
        ),
    ]
