# Generated by Django 4.0.3 on 2022-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0008_rename_parent_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='bank_accounts',
            field=models.ManyToManyField(to='ampa_members_manager.bankaccount'),
        ),
    ]
