# Generated by Django 4.0.3 on 2022-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0010_add_default_bank_account_to_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='families',
        ),
        migrations.AddField(
            model_name='family',
            name='parents',
            field=models.ManyToManyField(to='ampa_members_manager.parent'),
        ),
    ]
