# Generated by Django 4.0.6 on 2022-11-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0010_alter_parent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='email',
        ),
        migrations.RemoveField(
            model_name='family',
            name='secondary_email',
        ),
    ]
