# Generated by Django 4.0.3 on 2022-03-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0011_add_parents_to_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ampa_members_manager.bankaccount'),
        ),
    ]
