# Generated by Django 4.0.3 on 2022-03-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0012_default_bank_account_blank_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='bank_accounts',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.parent'),
            preserve_default=False,
        ),
    ]
