# Generated by Django 4.0.3 on 2022-03-28 21:44

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0013_add_owner_to_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=False),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='swift_bic',
            field=localflavor.generic.models.BICField(max_length=11),
        ),
    ]
