# Generated by Django 4.0.3 on 2022-03-29 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0015_use_phonenumber_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='year_of_birth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
