# Generated by Django 4.0.3 on 2022-03-29 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0016_use_year_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccourse',
            name='initialYear',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
