# Generated by Django 4.0.6 on 2022-12-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0016_add_after_school_remittance_and_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterschoolreceipt',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Total (€)'),
            preserve_default=False,
        ),
    ]
