# Generated by Django 4.0.3 on 2022-03-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0017_use_year_validator_in_academic_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.bankaccount')),
            ],
        ),
    ]
