# Generated by Django 4.0.3 on 2022-03-30 22:00

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0018_add_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=localflavor.generic.models.IBANField(include_countries=None, max_length=34, unique=True, use_nordea_extensions=False),
        ),
    ]
