# Generated by Django 4.0.6 on 2022-12-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0018_alter_authorization_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academiccourse',
            table='academic_course',
        ),
        migrations.AlterModelTable(
            name='activecourse',
            table='active_course',
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='activityperiod',
            table='activity_period',
        ),
        migrations.AlterModelTable(
            name='activityreceipt',
            table='activity_receipt',
        ),
        migrations.AlterModelTable(
            name='activityregistration',
            table='activity_registration',
        ),
        migrations.AlterModelTable(
            name='activityremittance',
            table='activity_remittance',
        ),
        migrations.AlterModelTable(
            name='afterschoolreceipt',
            table='after_school_receipt',
        ),
        migrations.AlterModelTable(
            name='afterschoolremittance',
            table='after_school_remittance',
        ),
        migrations.AlterModelTable(
            name='authorization',
            table='authorization',
        ),
        migrations.AlterModelTable(
            name='bankaccount',
            table='bank_account',
        ),
        migrations.AlterModelTable(
            name='child',
            table='child',
        ),
        migrations.AlterModelTable(
            name='family',
            table='family',
        ),
        migrations.AlterModelTable(
            name='fee',
            table='fee',
        ),
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
        migrations.AlterModelTable(
            name='membershipreceipt',
            table='membership_receipt',
        ),
        migrations.AlterModelTable(
            name='membershipremittance',
            table='membership_remittance',
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parent',
        ),
    ]
