# Generated by Django 4.0.3 on 2022-03-31 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0019_iban_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.academiccourse')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.family')),
            ],
        ),
    ]
