# Generated by Django 4.0.3 on 2022-03-31 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0020_add_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('single_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.singleactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepetitiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('single_activities', models.ManyToManyField(to='ampa_members_manager.singleactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
