# Generated by Django 4.0.3 on 2022-05-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0022_add_activity_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliarActivityRegistration',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ampa_members_manager.activityregistration',),
        ),
        migrations.CreateModel(
            name='IndividualActivityRegistration',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ampa_members_manager.activityregistration',),
        ),
    ]
