# Generated by Django 4.0.3 on 2022-05-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0025_add_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetitiveactivity',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='uniqueactivity',
            name='assignment',
        ),
    ]
