# Generated by Django 4.0.3 on 2022-05-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0028_remove_payment_order_as_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstablishedCourse',
            new_name='ActiveCourse',
        ),
    ]
