# Generated by Django 4.0.3 on 2022-05-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0029_rename_to_active_course'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='family',
            name='unique_surnames',
        ),
    ]
