# Generated by Django 4.0.3 on 2022-05-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0030_family_remove_constrain'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('name', 'family'), name='unique_child_name_in_a_family'),
        ),
    ]
