# Generated by Django 4.0.3 on 2022-05-14 22:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0031_add_child_name_and_family_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='additional_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
