# Generated by Django 4.0.3 on 2022-05-14 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0032_additional_phone_number_to_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='date',
        ),
        migrations.AddField(
            model_name='authorization',
            name='year',
            field=models.IntegerField(default=2022, unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)]),
            preserve_default=False,
        ),
    ]
