# Generated by Django 4.0.3 on 2022-05-14 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0033_change_date_to_year_in_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AddConstraint(
            model_name='authorization',
            constraint=models.UniqueConstraint(fields=('number', 'year'), name='unique_number_in_a_year'),
        ),
    ]
