# Generated by Django 4.0.3 on 2022-05-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0034_add_number_year_constraint_to_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
