# Generated by Django 4.0.3 on 2022-05-17 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0035_add_file_to_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccourse',
            name='initialYear',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)], verbose_name='Initial year'),
        ),
    ]
