# Generated by Django 4.0.3 on 2022-05-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0036_alter_academiccourse_initialyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academiccourse',
            old_name='initialYear',
            new_name='initial_year',
        ),
    ]
