# Generated by Django 4.0.3 on 2022-05-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0037_rename_initialYear'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_activities', models.ManyToManyField(to='ampa_members_manager.singleactivity')),
            ],
        ),
    ]
