# Generated by Django 4.0.3 on 2022-05-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0038_add_charge_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Created'), (2, 'Send'), (3, 'Paid')], default=1)),
                ('activity_registrations', models.ManyToManyField(to='ampa_members_manager.activityregistration')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.chargegroup')),
            ],
        ),
    ]
