# Generated by Django 4.0.3 on 2022-06-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0039_add_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityregistration',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.bankaccount'),
            preserve_default=False,
        ),
    ]
