# Generated by Django 4.0.5 on 2022-06-22 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0040_alter_activityregistration_bank_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccourse',
            options={'verbose_name': 'Academic course', 'verbose_name_plural': 'Academic courses'},
        ),
        migrations.AlterModelOptions(
            name='activecourse',
            options={'verbose_name': 'Active course', 'verbose_name_plural': 'Active course'},
        ),
        migrations.AlterModelOptions(
            name='activityregistration',
            options={'verbose_name': 'Activity registration', 'verbose_name_plural': 'Activity registrations'},
        ),
        migrations.AlterModelOptions(
            name='authorization',
            options={'verbose_name': 'Authorization', 'verbose_name_plural': 'Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Bank account', 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Membership'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='repetitiveactivity',
            options={'verbose_name': 'Repetitive activity', 'verbose_name_plural': 'Repetitive activities'},
        ),
        migrations.AlterModelOptions(
            name='singleactivity',
            options={'verbose_name': 'Single activity', 'verbose_name_plural': 'Single activities'},
        ),
        migrations.AlterModelOptions(
            name='uniqueactivity',
            options={'verbose_name': 'Unique activity', 'verbose_name_plural': 'Unique activities'},
        ),
        migrations.AlterField(
            model_name='academiccourse',
            name='fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='activecourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ampa_members_manager.academiccourse', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.bankaccount', verbose_name='Bank account'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='payment_order',
            field=models.FloatField(blank=True, null=True, verbose_name='Payment order'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='single_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.singleactivity', verbose_name='Single activity'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='bank_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.bankaccount', verbose_name='Bank account'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=localflavor.generic.models.IBANField(include_countries=None, max_length=34, unique=True, use_nordea_extensions=False, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.parent', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='swift_bic',
            field=localflavor.generic.models.BICField(max_length=11, verbose_name='SWIFT/BIC'),
        ),
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.family', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='repetition',
            field=models.IntegerField(default=0, verbose_name='Repetition'),
        ),
        migrations.AlterField(
            model_name='child',
            name='year_of_birth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)], verbose_name='Year of birth'),
        ),
        migrations.AlterField(
            model_name='family',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ampa_members_manager.bankaccount', verbose_name='Default bank account'),
        ),
        migrations.AlterField(
            model_name='family',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='family',
            name='first_surname',
            field=models.CharField(max_length=500, verbose_name='First surname'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parents',
            field=models.ManyToManyField(to='ampa_members_manager.parent', verbose_name='Parents'),
        ),
        migrations.AlterField(
            model_name='family',
            name='second_surname',
            field=models.CharField(max_length=500, verbose_name='Second surname'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='academic_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.academiccourse', verbose_name='Academic course'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.family', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='additional_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Additional phone number'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_surname',
            field=models.CharField(max_length=500, verbose_name='First surname'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='second_surname',
            field=models.CharField(max_length=500, verbose_name='Second surname'),
        ),
        migrations.AlterField(
            model_name='repetitiveactivity',
            name='academic_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.academiccourse', verbose_name='Academic course'),
        ),
        migrations.AlterField(
            model_name='repetitiveactivity',
            name='funding',
            field=models.IntegerField(choices=[(1, 'No Funding'), (2, 'Cultural'), (3, 'Sport')], verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='repetitiveactivity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='repetitiveactivity',
            name='single_activities',
            field=models.ManyToManyField(to='ampa_members_manager.singleactivity', verbose_name='Single activities'),
        ),
        migrations.AlterField(
            model_name='singleactivity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='singleactivity',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Per Day')], verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='singleactivity',
            name='price_for_member',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price for members'),
        ),
        migrations.AlterField(
            model_name='singleactivity',
            name='price_for_no_member',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price for no members'),
        ),
        migrations.AlterField(
            model_name='uniqueactivity',
            name='academic_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.academiccourse', verbose_name='Academic course'),
        ),
        migrations.AlterField(
            model_name='uniqueactivity',
            name='funding',
            field=models.IntegerField(choices=[(1, 'No Funding'), (2, 'Cultural'), (3, 'Sport')], verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='uniqueactivity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='uniqueactivity',
            name='single_activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.singleactivity', verbose_name='Single activity'),
        ),
    ]
