# Generated by Django 4.0.5 on 2022-06-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0041_add_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Email'),
        ),
    ]
