# Generated by Django 4.0.6 on 2022-07-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0043_alter_charge_options_alter_chargegroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityregistration',
            name='payment_order',
        ),
    ]
