# Generated by Django 4.0.6 on 2022-07-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0044_remove_payment_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charge',
            new_name='ActivityReceipt',
        ),
    ]
