# Generated by Django 4.0.6 on 2022-07-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0045_rename_charge_to_activity_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityreceipt',
            options={'verbose_name': 'Activity Receipt', 'verbose_name_plural': 'Activity Receipts'},
        ),
        migrations.RenameField(
            model_name='activityreceipt',
            old_name='group',
            new_name='remittance',
        ),
    ]
