# Generated by Django 4.0.6 on 2022-07-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0046_rename_group_to_remittance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreceipt',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.chargegroup', verbose_name='ActivityRemittance'),
        ),
    ]
