# Generated by Django 4.0.6 on 2022-07-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0048_rename_charge_group_to_activity_remittance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityremittance',
            options={'verbose_name': 'Activity Remittance', 'verbose_name_plural': 'Activity Remittances'},
        ),
    ]
