# Generated by Django 4.0.6 on 2022-07-20 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0049_rename_verbose_to_activity_remittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityremittance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 20, 16, 10, 5, 620769, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityremittance',
            name='name',
            field=models.CharField(default='GeneratedName', max_length=300, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
