# Generated by Django 4.0.6 on 2022-07-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0050_add_name_and_created_at_to_activity_remittance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetitiveactivity',
            name='single_activities',
        ),
        migrations.RemoveField(
            model_name='uniqueactivity',
            name='single_activity',
        ),
        migrations.AddField(
            model_name='singleactivity',
            name='repetitive_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.repetitiveactivity', verbose_name='Repetitive Activity'),
        ),
        migrations.AddField(
            model_name='singleactivity',
            name='unique_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.uniqueactivity', verbose_name='Unique activity'),
        ),
    ]
