# Generated by Django 4.0.6 on 2022-07-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0051_change_many_to_many_to_optional_foreign_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='singleactivity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('repetitive_activity', None), _negated=True), models.Q(('unique_activity', None), _negated=True), _connector='OR'), name='one_activity_reference'),
        ),
    ]
