# Generated by Django 4.0.6 on 2022-07-22 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0052_add_constraing_to_single_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleactivity',
            name='repetitive_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.repetitiveactivity', verbose_name='Repetitive Activity'),
        ),
        migrations.AlterField(
            model_name='singleactivity',
            name='unique_activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.uniqueactivity', verbose_name='Unique activity'),
        ),
    ]
