# Generated by Django 4.0.6 on 2022-07-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0053_activity_links_in_single_activity_blank_true'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='singleactivity',
            name='one_activity_reference',
        ),
        migrations.AddConstraint(
            model_name='singleactivity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('repetitive_activity__isnull', False), ('unique_activity__isnull', True)), models.Q(('repetitive_activity__isnull', True), ('unique_activity__isnull', False)), _connector='OR'), name='one_activity_reference'),
        ),
    ]
