# Generated by Django 4.0.6 on 2022-07-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0055_rename_single_activity_to_activity_payable_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitypayablepart',
            options={'verbose_name': 'Activity Payable Part', 'verbose_name_plural': 'Activity Payable Parts'},
        ),
        migrations.RenameField(
            model_name='activityregistration',
            old_name='single_activity',
            new_name='payable_part',
        ),
    ]
