# Generated by Django 4.0.6 on 2022-07-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0059_rename_verbose_single_activities_in_activity_remittance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.academiccourse', verbose_name='AcademicCourse')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Created'), (2, 'Send'), (3, 'Paid')], default=1, verbose_name='State')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.family', verbose_name='Family')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.membershipremittance', verbose_name='Membership Remittance')),
            ],
        ),
    ]
