# Generated by Django 4.0.6 on 2022-08-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0060_create_membership_remittance_and_receipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityPayablePart',
            new_name='ActivityPeriod',
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['owner', 'iban'], 'verbose_name': 'Bank account', 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.AlterField(
            model_name='activityreceipt',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.activityremittance', verbose_name='Activity remittance'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='authorizations/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='family',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, help_text='Save the family to see its bank accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ampa_members_manager.bankaccount', verbose_name='Default bank account'),
        ),
        migrations.AlterField(
            model_name='repetitiveactivity',
            name='funding',
            field=models.IntegerField(choices=[(1, 'No funding'), (2, 'Cultural'), (3, 'Sport')], verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='uniqueactivity',
            name='funding',
            field=models.IntegerField(choices=[(1, 'No funding'), (2, 'Cultural'), (3, 'Sport')], verbose_name='Funding'),
        ),
    ]
