# Generated by Django 4.0.6 on 2022-08-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0061_rename_activitypayablepart_activityperiod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityperiod',
            options={'verbose_name': 'Activity Period', 'verbose_name_plural': 'Activity Periods'},
        ),
    ]
