# Generated by Django 4.0.6 on 2022-08-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0064_activityperiod_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.activity', verbose_name='Activity'),
        ),
    ]
