# Generated by Django 4.0.6 on 2022-08-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampa_members_manager', '0065_alter_activityperiod_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetitiveactivity',
            name='academic_course',
        ),
        migrations.RemoveField(
            model_name='uniqueactivity',
            name='academic_course',
        ),
        migrations.RemoveConstraint(
            model_name='activityperiod',
            name='one_activity_reference',
        ),
        migrations.RemoveField(
            model_name='activityperiod',
            name='repetitive_activity',
        ),
        migrations.RemoveField(
            model_name='activityperiod',
            name='unique_activity',
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ampa_members_manager.activity', verbose_name='Activity'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RepetitiveActivity',
        ),
        migrations.DeleteModel(
            name='UniqueActivity',
        ),
    ]
