@startuml
abstract class Importation {
    dateTime : dateTime
    filename : str
}
class CustodyImportation {
    custodyEdition: CustodyEdition
}
class MembersImportation {
    custodyEdition: CustodyEdition
}
class CustodyImportationRow {
    row: int
}
class CustodyChildImportData {
    days_attended: int
}
class HolderImportData {
    iban: str
}
class ChildWithSurnamesImportData {
    surnames: str
}
class ChildImportData {
    name: str
    birth_year: Optional[int]
    level: Optional[LevelConstants]
}
class ParentImportData {
    holder_name_and_surnames: str
    phone_number: str
    email: str
}
abstract class CustodyImportationAction
abstract class CustodyImportationActionFamily
abstract class CustodyImportationActionChild
abstract class CustodyImportationActionHolder
class UseFamily
class UpdateFamily
class CreateFamily
class UseChild
class CreateChild
class UpdateChild
class UseHolder
class CreateHolder
class CreateCustodyRegistration

Importation <|-- CustodyImportation: ""
Importation <|-- MembersImportation: ""

CustodyImportation *-- "0..N" CustodyImportationRow: ""

CustodyImportationRow -- CustodyChildImportData: ""
CustodyImportationRow -- "0..1" HolderImportData: ""
CustodyImportationRow *-- "0..N" CustodyImportationAction: ""

CustodyChildImportData -- ChildWithSurnamesImportData: ""
ChildWithSurnamesImportData -- ChildImportData: ""

HolderImportData -- ParentImportData: ""

CustodyImportationAction <|-- CustodyImportationActionFamily: ""
CustodyImportationAction <|-- CreateCustodyRegistration: ""
CustodyImportationAction <|-- CustodyImportationActionChild: ""
CustodyImportationAction <|-- CustodyImportationActionHolder: ""
CustodyImportationActionFamily <|-- UseFamily: ""
CustodyImportationActionFamily <|-- CreateFamily: ""
CustodyImportationActionFamily <|-- UpdateFamily: ""
CustodyImportationActionChild <|-- UseChild: ""
CustodyImportationActionChild <|-- CreateChild: ""
CustodyImportationActionChild <|-- UpdateChild: ""
CustodyImportationActionHolder <|-- UseHolder: ""
CustodyImportationActionHolder <|-- CreateHolder: ""
@enduml
