@startuml
abstract class Importation {
    dateTime : dateTime
    filename : str
}
class CustodyImportation {
    custodyEdition: CustodyEdition
}
class MembersImportation {
    custodyEdition: CustodyEdition
}
class CustodyImportationRow {
    row: int
}
class CustodyChildImportData {
    days_attended: int
}
class HolderImportData {
    iban: str
}
class ChildWithSurnamesImportData {
    surnames: str
}
class ChildImportData {
    name: str
    birth_year: Optional[int]
    level: Optional[LevelConstants]
}
class ParentImportData {
    holder_name_and_surnames: str
    phone_number: str
    email: str
}
abstract class CustodyImportationActionGroup
abstract class CustodyImportationActionFamily {
    family: Family
}
abstract class CustodyImportationActionChild {
    child: Child
}
abstract class CustodyImportationActionHolder {
    holder: Holder
}
class UseFamily
class UpdateFamily {
    data_to_change: ...
}
class CreateFamily {
    data_to_create: ...
}
class UseChild
class UpdateChild {
    data_to_change: ...
}
class CreateChild {
    data_to_create: ...
}
class UseHolder
class CreateHolder {
    data_to_create: ...
}
class CreateCustodyRegistration

Importation <|-- CustodyImportation: ""
Importation <|-- MembersImportation: ""

CustodyImportation *-- "0..N" CustodyImportationRow: ""

CustodyImportationRow -- CustodyChildImportData: ""
CustodyImportationRow -- "0..1" HolderImportData: ""
CustodyImportationRow *-- CustodyImportationActionGroup: ""

CustodyChildImportData -- ChildWithSurnamesImportData: ""
ChildWithSurnamesImportData -- ChildImportData: ""

HolderImportData -- ParentImportData: ""

CustodyImportationActionGroup -- CustodyImportationActionFamily: ""
CustodyImportationActionGroup -- CreateCustodyRegistration: ""
CustodyImportationActionGroup -- CustodyImportationActionChild: ""
CustodyImportationActionGroup -- CustodyImportationActionHolder: ""
CustodyImportationActionFamily <|-- UseFamily: ""
CustodyImportationActionFamily <|-- CreateFamily: ""
CustodyImportationActionFamily <|-- UpdateFamily: ""
CustodyImportationActionChild <|-- UseChild: ""
CustodyImportationActionChild <|-- CreateChild: ""
CustodyImportationActionChild <|-- UpdateChild: ""
CustodyImportationActionHolder <|-- UseHolder: ""
CustodyImportationActionHolder <|-- CreateHolder: ""
@enduml
